= Student Enrollment Agreement

This contract, together with the school catalog, it will constitute a binding agreement upon acceptance by the institution and the student.

== Student Information

|===
|Name
|Address
|Telephone
|Date of Birth
|SSN
|Email
|===

== Program Information

|===
|Program Title
|Clock Hours
|Credit Hours
|Hours per week
|Start Date
|Expected End Date
|===

== Tuition

- [ ] Full payment at time of signing enrollment agreement; OR
- [ ] $1,000 Down payment at time of signing enrollment agreement with balance paid prior to program start date.

|===
|Program Tuition Cost:
|Scholarship Awards (if any):
|Total tuition cost:
|===

=== Method of Payment
   
- [ ] Credit
- [ ] Check
- [ ] Money Order
- [ ] Other:

All prices for program are printed herein. Contracts are not sold to a third party at any time. There are no carryingcharges, interest charges, or service charges connected or charged with any of these programs unless stated.

== Cancellation and Refund Policy

{% include "./_refund-policy.adoc" %}

== Grounds for Termination

The student’s enrollment can be terminated at the discretion of the institution for lack of academic progress, non-payment of tuition or fees, or failing to comply with policies established in the Catalog and this agreement.

== Employment Assistance

Career support and placement assistance may be offered by the institution, but do not guarantee employment.

== Acknowledgement

This Agreement and the Catalog constitute a binding contract between the institution and the student and no further modification or representation except as herein expressed by both parties will be recognized.

== Credential Awarded

Upon the successful completion of the program, the student will receive a:

**Certification of Completion in Web Development**

---

IMPORTANT: Before signing this contract; ensure you have read it, and it contains no blank spaces. By signing this contract you acknowledge you have read and received a copy of the binding document and catalog.


|===
|Signature of Applicant +
|Date
|===

|===
|Signature of School Official +
|Date
|===


