= Student Enrollment Agreement

This contract, together with the school catalog, will constitute a binding agreement upon acceptance by Suncoast Developers Guild (the institution) and the student.

== School Information
Suncoast Developers Guild
244 2nd Ave N, Suite 9
St. Petersburg, FL 33701
(727) 201-2012

== Student Information

|===
|Name
|Address
|Telephone
|Date of Birth
|Email
|===

== Program Information

|===
|Program Title: Web Development
|Clock Hours: 396 (3 months)
|Start Date
|Expected End Date
|===

== Tuition

- [ ] Full payment at time of signing enrollment agreement; OR
- [ ] $1,000 Down payment at time of signing enrollment agreement with balance paid prior to program start date.

|===
|Program Tuition Cost:
|Scholarship Awards (if any):
|Total tuition cost:
|===

=== Method of Payment
   
- [ ] Credit
- [ ] Check
- [ ] Money Order
- [ ] Other:

All prices for program are printed herein. Contracts are not sold to a third party at any time. There are no carryingcharges, interest charges, or service charges connected or charged with any of these programs unless stated.

== Cancellation and Refund Policy

The following refund policy will be followed if a student's enrollment in the program is terminated for any reason:

. Cancellation or termination can be made in person, by email, or by certified mail.
. Any collected funds will be returned if an applicant is not accepted to the program.
. Students accepted to the program will be returned all funds if enrollment is cancelled within three (3) business days of signing the enrollment agreement.
. In the event of cancellation after program attendance has begun, funds will be returned Pro Rata up to 40% of total program hours, based on the number of completed hours.
. No funds will be returned after 40% completion of the program.
. In calculating refunds, the last date of actual attendance is used to determine completed hours.
. Any refunds due will be made within 30 days of
.. receiving notice of cancellation from the student;
.. or termination of the student by the school.

== Grounds for Termination

The student’s enrollment can be terminated at the discretion of the institution for lack of academic progress, non-payment of tuition or fees, or failing to comply with policies established in the Catalog and this agreement.

== Employment Assistance

Career support and placement assistance may be offered by the institution, but do not guarantee employment.

== Acknowledgement

This Agreement and the Catalog constitute a binding contract between the institution and the student and no further modification or representation except as herein expressed by both parties will be recognized.

== Credential Awarded

Upon the successful completion of the program, the student will receive a:

**Certification of Completion in Web Development**

---

IMPORTANT: Before signing this contract; ensure you have read it, and it contains no blank spaces. By signing this contract you acknowledge you have read and received a copy of the binding document and catalog.


|===
|Signature of Applicant +
|Date
|===

|===
|Signature of Institution Official +
|Date
|===


